#import "./PodListing.fragment.graphql"
#import "./PodOrder.fragment.graphql"
#import "./PodFill.fragment.graphql"

query AllMarketActivity(
  $first: Int = 1000
  $listings_createdAt_gt: BigInt
  $orders_createdAt_gt: BigInt
  $fill_createdAt_gt: BigInt
  $listings_podMarketplace: String
  $orders_podMarketplace: String
) {
  podListings(
    first: $first
    where: {
      createdAt_gt: $listings_createdAt_gt
      status_not: FILLED_PARTIAL
      podMarketplace: $listings_podMarketplace
    }
  ) {
    ...PodListing
  }

  podOrders(
    first: $first
    orderBy: createdAt
    orderDirection: desc
    where: {
      createdAt_gt: $orders_createdAt_gt
      podMarketplace: $orders_podMarketplace
    }
  ) {
    ...PodOrder
  }

  podFills(first: $first, where: { createdAt_gt: $fill_createdAt_gt }) {
    ...PodFill
  }
}
