query BeanstalkAdvancedChart(
  $seasonsWhere: String
  $seasonsOrderBy: String
  $seasonsOrderDirection: String
  $fieldWhere: String
  $fieldOrderBy: String
  $fieldOrderDirection: String
  $siloWhere: String
  $siloOrderBy: String
  $siloOrderDirection: String
) {
  seasons: cache_seasons(
    where: $seasonsWhere
    orderBy: $seasonsOrderBy
    orderDirection: $seasonsOrderDirection
  ) {
    id
    sunriseBlock
    rewardBeans
    price
    deltaBeans
    season
    createdAt
  }
  fieldHourlySnapshots: cache_fieldHourlySnapshots(
    where: $fieldWhere
    orderBy: $fieldOrderBy
    orderDirection: $fieldOrderDirection
  ) {
    id
    caseId
    issuedSoil
    deltaSownBeans
    sownBeans
    blocksToSoldOutSoil
    podRate
    temperature
    deltaTemperature
    season
    harvestableIndex
    harvestablePods
    harvestedPods
    numberOfSowers
    numberOfSows
    podIndex
    realRateOfReturn
    seasonBlock
    soil
    soilSoldOut
    unharvestablePods
  }
  siloHourlySnapshots: cache_siloHourlySnapshots(
    where: $siloWhere
    orderBy: $siloOrderBy
    orderDirection: $siloOrderDirection
  ) {
    id
    beanToMaxLpGpPerBdvRatio
    season
    stalk
    caseId
  }
}
